- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  notify: Restart nginx

- name: config file
  ansible.builtin.copy:
    dest: /etc/nginx/sites-enabled/default 
    src: default
  notify: Restart nginx