- name: Nginx package
  ansible.builtin.apt:
    name: nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Config file
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/default 
    src: default.j2
  notify: Restart nginx

- name: Nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Nginx exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
  notify: Restart nginx exporter