- name: Nginx package
  ansible.builtin.apt:
    name: nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Config file
  ansible.builtin.copy:
    dest: /etc/nginx/sites-enabled/default 
    src: default
  notify: Restart nginx