- name: Nginx packages
  ansible.builtin.apt:
    name: 
    - nginx
    - prometheus-nginx-exporter

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Config file
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/default 
    src: default.j2
  notify: 
    - Restart nginx
    - Restart nginx exporter

- name: Nginx services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter