- name: Haproxy packages
  ansible.builtin.apt:
    name: 
     - haproxy
     - prometheus-haproxy-exporter

- name: Haproxy Config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Haproxy exporter config
  ansible.builtin.copy:
    src: prometheus-haproxy-exporter
    dest: /etc/default/prometheus-haproxy-exporter
  notify: 
    - Restart haproxy exporter
    - Restart haproxy

- name: Haproxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Haproxy exporter service
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: yes

- name: CNAME record
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record: "lb{{ inventory_hostname | replace('EphemeralShine', '') }}"