- name: InfluxDB GPG key
  ansible.builtin.apt_key: 
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: InfluxDB repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main

- name: InfluxDB
  ansible.builtin.apt:
    name: influxdb

- name: InfluxDB config
  ansible.builtin.copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: yes

- name: Influxdb stats exporter binary
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: u+x
    owner: prometheus

- name: Influxdb stats exporter service config 
  ansible.builtin.copy:
    src: prometheus-influxdb-stats-exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    mode: 0644
  notify: Reload systemd

- name: Influx stats exporter service
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes

- name: InfluxData for telegraf GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive.key

- name: InfluxData for telegraf repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable

- name: Telegraf 1.28.2
  ansible.builtin.apt:
    name: telegraf=1.28.2-1

- name: Telegraf config
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: yes

- name: Backup directory
  ansible.builtin.file:
    state: directory
    owner: backup
    path: /home/backup/influxdb
    mode: 600