- name: InfluxDB GPG key
  ansible.builtin.apt_key: 
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: InfluxDB repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main

- name: InfluxDB
  ansible.builtin.apt:
    name: influxdb

- name: InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: yes

- name: InfluxData for telegraf GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive.key

- name: InfluxData for telegraf repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable

- name: Telegraf 1.28.2
  ansible.builtin.apt:
    name: telegraf=1.28.2-1

- name: Telegraf config
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: yes