- name: Grafana directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  loop: 
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Grafana config
  ansible.builtin.template:
    mode: 0600
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: Restart grafana

- name: Grafana dashboards config
  ansible.builtin.copy:
   dest: /opt/grafana/provisioning/dashboards/default.yaml
   src: main.yaml

- name: Grafana datasource
  ansible.builtin.copy:
   dest: /opt/grafana/provisioning/datasources/default.yaml
   src: datasources.yaml

- name: Grafana dashboards jsons
  ansible.builtin.copy:
    dest: /opt/grafana/provisioning/dashboards/
    src: "{{ item }}"
  loop:
    - main.json
    - mysql.json
    - syslog.json

- name: Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    user: root
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always

- name: CNAME record
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record: grafana
