- name: Grafana gpg key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Grafana
  ansible.builtin.apt:
    name: grafana

- name: Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Grafana reverse proxy
  ansible.builtin.template:
    dest: /etc/grafana/grafana.ini
    src: grafana.ini.j2
  notify: Restart grafana

- name: Grafana jsons
  ansible.builtin.copy:
    dest: /etc/grafana/dashboards/main.json
    src: main.json
  notify: Restart grafana

- name: Grafana datasource
  ansible.builtin.copy:
   dest: /etc/grafana/provisioning/datasources/sample.yaml
   src: prometheusdt.yaml
  notify: Restart grafana

- name: Grafana dashboard
  ansible.builtin.copy:
   dest: /etc/grafana/provisioning/dashboards/sample.yaml
   src: main.yaml
  notify: Restart grafana
  