- name: uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: uWSGI configuration
  ansible.builtin.copy:
    dest: /etc/uwsgi/apps-enabled/agama.ini
    src: agama.ini
    owner: agama
  notify: Restart uWSGI

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

