- name: uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: uWSGI configuration
  ansible.builtin.template:
    dest: /etc/uwsgi/apps-enabled/agama.ini
    src: agama.ini.j2
    owner: agama
    mode: 0600
  no_log: true
  notify: Restart uWSGI

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

