- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: pinger
    state: restarted

- name: Restart pinger
  ansible.builtin.service:
    name: pinger
    state: restarted