{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 0 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Haproxy agama containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up\r\n", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "DNS type A queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 2, "y": 4 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 4 },
   "targets": [
    {
     "alias": "github",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\" = 'github.com') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "8.8.8.8" }
     ]
    },
    {
     "alias": "8.8.8.8",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\" = '8.8.8.8') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "8.8.8.8" }
     ]
    },
    {
     "alias": "itcollege",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\" = 'itcollege.ee') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "8.8.8.8" }
     ]
    },
    {
     "alias": "EphemeralShine-2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "query": "SELECT mean(\"rtt\") FROM \"rtt\" WHERE (\"dst\" = 'EphemeralShine-2') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "8.8.8.8" }
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Haproxy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived VRRP state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}