- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: keepalived-exporter
    state: restarted

- name: Restart keepalived exporter
  ansible.builtin.service:
    name: keepalived-exporter
    state: restarted