- name: Mysql exporter config
  ansible.builtin.template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
    owner: prometheus
    mode: 0600
  no_log: true

- name: Mysql packages
  ansible.builtin.apt:
   name: 
   - mysql-server
   - python3-pymysql
   - prometheus-mysqld-exporter


- name: Mysql config
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql
  
- name: Mysql services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - mysql
    - prometheus-mysqld-exporter

- name: Database creation
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: MySQL agama user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    priv: 
      '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify: Restart mysql exporter

- name: MySQL replication user
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql
  
- name: Backup directory
  ansible.builtin.file:
    state: directory
    owner: backup
    group: backup
    path: /home/backup/mysql
    mode: 0755

- name: Backup user
  community.mysql.mysql_user:
    name: "{{ mysql_backup_user }}"
    host: "%"
    password: "{{mysql_backup_password}}"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql

- name: Mysql exporter config
  ansible.builtin.template:
    dest: /home/backup/.my.cnf
    src: my.backupcnf.j2
    owner: backup
    mode: 0600
  no_log: true

- name: Cron tab for mysql backup
  ansible.builtin.template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup

- name: Slave metrics
  ansible.builtin.copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter 
  notify: Restart mysql exporter

- name: MySQL replica read-only mode
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: CNAME record
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record: "mysql{{ inventory_hostname | replace('EphemeralShine', '') }}"