- name: Mysql package
  ansible.builtin.apt:
   name: mysql-server

- name: Mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Python library for mysql
  ansible.builtin.apt:
   name: python3-pymysql

- name: Database creation
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Mysql config
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

