- name: Mysql package
  ansible.builtin.apt:
   name: mysql-server

- name: Mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Python library for mysql
  ansible.builtin.apt:
   name: python3-pymysql

- name: Database creation
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Mysql config
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    priv: 
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify: Restart mysql exporter

- name: Mysql exporter config
  ansible.builtin.template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
    owner: prometheus
    mode: 0600
  no_log: true
  notify: Restart mysql exporter

- name: Mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Mysql exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true
  

