- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus-influxdb-stats-exporter
    state: restarted