- name: Keepalived packages
  ansible.builtin.apt:
    name: keepalived

- name: Keepalived script user
  ansible.builtin.user:
    name: keepalived_script
    home: /home/keepalived_script
    shell: /bin/bash

- name: Keepalived Config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0600
  no_log: true
  notify: Restart keepalived

- name: Keepalived script file
  ansible.builtin.copy:
    src: vrrp_script
    dest: /home/keepalived_script/vrrp_script
    owner: keepalived_script
    mode: 0700

- name: Keepalived exporter archive
  ansible.builtin.unarchive:
    dest: /var/lib/
    src: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    remote_src: yes

- name: Keepalived exporter binary
  ansible.builtin.copy:
    dest: /usr/local/bin/keepalived-exporter
    src: /tmp/keepalived-exporter-1.2.0.linux-amd64/keepalived-exporter
    mode: 0700
    remote_src: yes
  notify: Restart keepalived exporter

- name: Keepalived exporter service config
  ansible.builtin.copy:
    dest: /etc/systemd/system/
    src: keepalived-exporter.service
  notify: Reload systemd

- name: Keepalived service
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes

- name: Keepalived exporter service
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: yes
