#- name: Ansible ping module
# ansible.builtin.ping:

# - name: Juri user module
#   ansible.builtin.user:
#     name: juri

# - name: Roman user module
#   ansible.builtin.user:
#     name: roman

# - name: Juri authorized key module
#   ansible.posix.authorized_key:
#     user: juri
#     key: https://github.com/hudolejev.keys

# - name: Roman authorized key module
#   ansible.posix.authorized_key:
#     user: roman
#     key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name : Prometheus node exporters and certs
  ansible.builtin.apt:
    name: 
    - prometheus-node-exporter
    - ca-certificates>=20230311ubuntu0.20.04.1

- name: prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Rsyslog config
  ansible.builtin.copy:
   src: 10-telegraf.conf
   dest: /etc/rsyslog.d/10-telegraf.conf
  notify: Restart rsyslog
