- name: Stop systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Resolve configuration
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: CNAME record
  ansible.builtin.include_role:
    name: dns_record
  vars:
    dns_record: "ns{{ inventory_hostname | replace('EphemeralShine', '') }}"

- name: Rsyslog config
  ansible.builtin.copy:
   src: 10-telegraf.conf
   dest: /etc/rsyslog.d/10-telegraf.conf
  notify: Restart rsyslog